# Generated by Django 4.1.7 on 2023-05-28 00:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taller.validaciones


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre del alumno', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del alumno', max_length=50, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento', validators=[taller.validaciones.ValEdadAlumno], verbose_name='Nacimiento')),
                ('mail', models.EmailField(help_text='Mail de contacto', max_length=30, validators=[taller.validaciones.ValMail], verbose_name='Mail')),
                ('celular', models.CharField(help_text='Celular de contacto', max_length=20, validators=[taller.validaciones.ValCelular], verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('SUG', 'Sugerencia'), ('CON', 'Consulta'), ('SUS', 'Suscripción')], help_text='Motivo del contacto', max_length=3, verbose_name='Motivo')),
                ('nombre', models.CharField(help_text='Nombre', max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido', max_length=50, verbose_name='Apellido')),
                ('mail', models.EmailField(help_text='Mail', max_length=30, verbose_name='Mail')),
                ('comentario', models.CharField(blank=True, help_text='Comentario', max_length=500, null=True, verbose_name='Comentario')),
                ('fecha', models.DateField(default=django.utils.timezone.now, help_text='Fecha', verbose_name='Fecha')),
                ('revisado', models.BooleanField(default=False, help_text='Revisado', verbose_name='Revisado')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.IntegerField(help_text='Código de curso', primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo', models.CharField(help_text='Nombre del curso', max_length=50, verbose_name='Curso')),
                ('imagen', models.CharField(help_text='Imagen curso', max_length=30, verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='galeria/')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('fecha', models.DateField(default='1900-01-01', verbose_name='Fecha')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('destacado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('turno_id', models.AutoField(primary_key=True, serialize=False)),
                ('descripción', models.CharField(help_text='Datos del turno', max_length=50, verbose_name='Dictado')),
                ('anio', models.IntegerField(help_text='Año de dictado', verbose_name='Año')),
                ('destinatario', models.CharField(choices=[('N', 'Niños'), ('J', 'Jóvenes'), ('A', 'Adultos')], default='J', help_text='Destinatarios', max_length=1, verbose_name='Destinatarios')),
                ('experiencia', models.CharField(choices=[('SE', 'Sin Experiencia'), ('CE', 'Con Experiencia'), ('AV', 'Avanzado')], default='SE', help_text='Experiencia', max_length=2, verbose_name='Experiencia')),
                ('cupo', models.IntegerField(help_text='Cupo', verbose_name='Cupo')),
                ('alumnos', models.ManyToManyField(through='taller.Inscripcion', to='taller.alumno')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.curso')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='turno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.turno'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno_id', 'turno_id')},
        ),
        migrations.CreateModel(
            name='CursoDescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_id', models.IntegerField(help_text='Posición de la descripción', verbose_name='Posición')),
                ('descripcion', models.CharField(help_text='Descripción', max_length=150, verbose_name='Descripción')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.curso')),
            ],
            options={
                'unique_together': {('curso_id', 'posicion_id')},
            },
        ),
    ]
