# Generated by Django 4.1.7 on 2023-05-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('curso_id', models.IntegerField(help_text='Código de curso', primary_key=True, serialize=False, verbose_name='Código')),
                ('titulo', models.CharField(help_text='Nombre del curso', max_length=50, verbose_name='Curso')),
                ('imagen', models.CharField(help_text='Imagen curso', max_length=30, verbose_name='Imagen')),
            ],
        ),
        migrations.CreateModel(
            name='CursoDescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_id', models.IntegerField(help_text='Posición de la descripción', verbose_name='Posición')),
                ('descripcion', models.CharField(help_text='Descripción', max_length=150, verbose_name='Descripción')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.curso')),
            ],
            options={
                'unique_together': {('curso_id', 'posicion_id')},
            },
        ),
    ]
