# Generated by Django 4.1.5 on 2023-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='imagen',
            field=models.FileField(upload_to='galeria/'),
        ),
    ]
