# Generated by Django 4.1.7 on 2023-05-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0001_cursos_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(help_text='Motivo del contacto', max_length=3, verbose_name='Motivo')),
                ('nombre', models.CharField(help_text='Nombre', max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido', max_length=50, verbose_name='Apellido')),
                ('mail', models.EmailField(help_text='Mail', max_length=30, verbose_name='Mail')),
                ('comentario', models.CharField(blank=True, help_text='Comentario', max_length=500, null=True, verbose_name='Comentario')),
            ],
        ),
    ]
