# Generated by Django 4.1.5 on 2023-05-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0002_Contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='galeria/')),
                ('titulo', models.CharField(max_length=100, verbose_name='Título')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('fecha', models.DateField(default='1900-01-01', verbose_name='Fecha')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('destacado', models.BooleanField(default=False)),
            ],
        ),
    ]
