# Generated by Django 4.1.7 on 2023-05-26 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0003_trabajo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('alumno_id', models.IntegerField(help_text='Código de alumno', primary_key=True, serialize=False, verbose_name='Alumno')),
                ('nombre', models.CharField(help_text='Nombre del alumno', max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(help_text='Apellido del alumno', max_length=50, verbose_name='Apellido')),
                ('fecha_nacimiento', models.DateField(help_text='Fecha de nacimiento', verbose_name='Nacimiento')),
                ('mail', models.EmailField(help_text='Mail de contacto', max_length=30, verbose_name='Mail')),
                ('celular', models.CharField(help_text='Celular de contacto', max_length=20, verbose_name='Celular')),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.alumno')),
            ],
        ),
        migrations.AddField(
            model_name='contacto',
            name='revisado',
            field=models.BooleanField(default=False, help_text='Revisado', verbose_name='Revisado'),
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('turno_id', models.IntegerField(help_text='Código de turno', primary_key=True, serialize=False, verbose_name='Turno')),
                ('descripción', models.CharField(help_text='Datos del turno', max_length=50, verbose_name='Dictado')),
                ('anio', models.IntegerField(help_text='Año de dictado', verbose_name='Año')),
                ('destinatario', models.CharField(choices=[('N', 'Niños'), ('J', 'Jóvenes'), ('A', 'Adultos')], default='J', help_text='Destinatarios', max_length=1, verbose_name='Destinatarios')),
                ('experiencia', models.CharField(choices=[('SE', 'Sin Experiencia'), ('CE', 'Con Experiencia'), ('AV', 'Avanzado')], default='SE', help_text='Experiencia', max_length=2, verbose_name='Experiencia')),
                ('cupo', models.IntegerField(help_text='Cupo', verbose_name='Cupo')),
                ('alumnos', models.ManyToManyField(through='taller.Inscripcion', to='taller.alumno')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.curso')),
            ],
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='turno_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taller.turno'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno_id', 'turno_id')},
        ),
    ]
