# Generated by Django 4.1.7 on 2023-05-26 19:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0004_ContactoAlumnoTurno'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, help_text='Fecha', verbose_name='Fecha'),
        ),
    ]
