# Generated by Django 4.1.7 on 2023-05-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taller', '0005_FechaContacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='motivo',
            field=models.CharField(choices=[('SUG', 'Sugerencia'), ('CON', 'Consulta'), ('SUS', 'Suscripción')], help_text='Motivo del contacto', max_length=3, verbose_name='Motivo'),
        ),
    ]
